modLoader = "javafml"
loaderVersion = "[36.2,)"
license = "MIT"

[[mods]] 
modId = "gigawhat_gigamod" 
version = "0.2.0"
displayName = "Gigamod (Beta)"
#logoFile = "examplemod.png"
authors = "Gigawhat Programing Team"
credits = "Samyar Sadat Akhavi, Hikmet Umut Bulut, Ekin Aksu"
description = '''
Gigamod, a mod by Gigawhat for the Gigawhat Minecraft server.



§6§l§o------- Credits -------§r

§b§o---- Code ----§r
§aLead developer : Samyar Sadat Akhavi
§3Developer : Ekin Aksu

§e§o---- Textures & Models ----§r
§7Texture design : Hikmet Umut Bulut, Samyar Sadat Akhavi
§7Modeling : Samyar Sadat Akhavi

§9§o---- Sound ----§r
§7Sound design : Samyar Sadat Akhavi, Ekin Aksu

§a§o---- Testing ----§r
§7Gigawhat Programing Team


§dCopyright © 2021 Gigawhat Programing Team.'''

[[dependencies.gigawhat_gigamod]]

    modId = "forge"
    mandatory = true
    versionRange = "[36.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gigawhat_gigamod]]

    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16, 1.16.5)"
    ordering = "NONE"
    side = "BOTH"
