name: Build on Mac OS latest

on:
  push:
    branches: [dev, 1.16.x]
  pull_request:
    branches: [dev, 1.16.x]

jobs:
  build:
    name: Build and upload jar file (Mac OS)
    runs-on: macos-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles("**/*.gradle*") }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: "temurin"

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
        
    - name: Archive jars on GitHub
      uses: actions/upload-artifact@v2
      with:
        name: JAR_FILE
        path: build/libs/